### PR TITLE
add Vietnamese (vi) language

### PR DESCRIPTION
**Pull request by KhanhNguyen9872**

### CODE REVIEW

**Review by DevVali — CHANGES_REQUESTED** [review]
Please, edit the `~/langs.php` with the language you translated to. 

## What I mean?
The `language` option with how you say `Vietnamese` in the language you were translating to (Vietnamese).

**Comment by KhanhNguyen9872** [comment]
> 

i already edit langs.php bro
```bash
...
  "language" => "Español",
  "code" => "es",
  ],

  [
  "language" => "Vietnamese",
  "code" => "vi",
  ],

];
```

**Comment by DevVali** [comment]
> 

Hi, I meant how you say `Vietnamese` or `Vietnamese language` in Vietnamese language. As you can see the other names of languages aren't in English.

**Comment by KhanhNguyen9872** [comment]
> > 
> 
> Hi, I meant how you say `Vietnamese` or `Vietnamese language` in Vietnamese language. As you can see the other names of languages aren't in English.

okay bro <3

**Review by Natasquare — CHANGES_REQUESTED** [review]
In my opinion, just `Lưu` is already enough for the `saveLabel`, since it's a small button so the text should be as small as possible, shouldn't it? Also `Tải tệp lên từ thiết bị của bạn` would be better for the `loadDescr` since:
1. It includes *the thing* that you upload;
2. `máy tính` (computer) is too specific! `thiết bị` (device) would be better since the user can be on mobile or other devices too.

Also maybe translate `online code editor` to something else idk.

**Comment by DevVali** [comment]
In the EN translation `~/lang/en.phl` is "computer", since fiddleit isn't meant to be used for mobile devices (atm).

**Comment by Natasquare** [comment]
I see. But so that we won't have to change it later.

**Comment by DevVali** [comment]
> I see. But so that we won't have to change it later.

We've also done 5+ other translations so it would be weird to have there computer and in this one device.

**Comment by KhanhNguyen9872** [comment]
> In my opinion, just `Lưu` is already enough for the `saveLabel`, since it's a small button so the text should be as small as possible, shouldn't it? Also `Tải tệp lên từ thiết bị của bạn` would be better for the `loadDescr` since:
> 
> 1. It includes _the thing_ that you upload;
> 2. `máy tính` (computer) is too specific! `thiết bị` (device) would be better since the user can be on mobile or other devices too.
> 
> Also maybe translate `online code editor` to something else idk.

`online code editor` is the program name, no need to translate it into Vietnamese

**Comment by Natasquare** [comment]
So just
```diff
- Lưu lại
+ Lưu
```
?

**Comment by DevVali** [comment]
@KhanhNguyen9872 @Natasquare could you resolve the conflicts so i can merge this PR asap? 

Thanks, DevVali

**Comment by DevVali** [comment]
(accidently closed)

**Review by DevVali — APPROVED** [review]
Ready to be merged.

**Pull request merged**
